lsi:        false
permalink:  pretty
pygments:   true
safe:       true

config:
    author:
        email: taylor@fausak.me
        name: Taylor Fausak
    fb_admins: 100001771158100
    title: taylor.fausak.me
    url: 'http://taylor.fausak.me'
