charset: utf-8
language: en-US
title: taylor.fausak.me



author:
    name:   Taylor Fausak
    email:  taylor@fausak.me
permalink:  pretty
title:      taylor.fausak.me
url:        http://taylor.fausak.me
