defaults:
- scope:
    path: ''
    type: post
  values:
    layout: post
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- LICENSE.txt
- README.md
- Rakefile
- Vagrantfile
- vendor
lsi: false
permalink: pretty
safe: true
sass:
  sass_dir: static/styles
timezone: America/Chicago
