author:
    name:   Taylor Fausak
    email:  taylor@fausak.me
lsi:        false
permalink:  pretty
pygments:   true
safe:       true
title:      taylor.fausak.me
url:        'http://taylor.fausak.me'
