exclude:
-   CNAME
-   Gemfile
-   Gemfile.lock
-   LICENSE.txt
-   README.md
-   Rakefile
-   Vagrantfile
-   vendor
permalink: pretty
timezone: America/Chicago

# https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
lsi: false
pygments: true
safe: true
