# GitHub Pages forces these options.
# https://help.github.com/articles/using-jekyll-with-pages#troubleshooting
lsi: false
pygments: true
safe: true

# Use this URL format: "/:year/:month/:day/:title/".
# https://github.com/mojombo/jekyll/wiki/Permalinks#built-in-styles
permalink: pretty

# Keep the site DRY by customizing things here.
config:
    author:
        email: taylor@fausak.me
        facebook_id: 100001771158100
        name: Taylor Fausak
        twitter_id: 204457677
    title: taylor.fausak.me
    url: 'http://taylor.fausak.me'
