defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
exclude:
- CNAME
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- Rakefile
gems:
- jekyll-sitemap
kramdown:
  input: GFM
lsi: false
permalink: pretty
sass:
  sass_dir: static/styles
timezone: America/Chicago
